version: '3'
services:
  cassandra:
    container_name: cassandra
    image: cassandra:latest
    volumes: 
      - cassandra:/var/lib/cassandra
    networks:
      - glowroot_net

  glowroot:
    container_name: glowroot
    image: seepen/glowroot-central
    ports:
      - "4000:4000"
      - "8181:8181"
    volumes:
      - ./glowroot-central.properties:/glowroot-central/glowroot-central.properties
    networks:
      - glowroot_net

volumes:
  cassandra: {}
  
networks: 
  glowroot_net:
  